name: Deploy to Azure Functions

on:
  push:
    branches:
      - main  # Replace with your deployment branch

env:
  AZURE_FUNCTIONAPP_NAME_1: multiple-functions-github-action-test-func1   # Replace with your first Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH_1: func1  # Replace with the path to your first project
  AZURE_FUNCTIONAPP_NAME_2: multiple-functions-github-action-test-func2   # Replace with your second Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH_2: func2  # Replace with the path to your second project

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v2

    - name: 'Setup Python'
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: 'Print Environment Variables'
      run: |
        echo "AZURE_FUNCTIONAPP_NAME_1: ${{ env.AZURE_FUNCTIONAPP_NAME_1 }}"
        echo "AZURE_FUNCTIONAPP_NAME_2: ${{ env.AZURE_FUNCTIONAPP_NAME_2 }}"
      shell: bash

    - name: 'Install dependencies for Project 1'
      run: |
        pip install -r requirements.txt
      working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_1 }}
    - name: 'Build Project 1'
      run: |
        func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME_1 }} --python
      working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_1 }}

    - name: 'Install dependencies for Project 2'
      run: |
        pip install -r requirements.txt
      working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_2 }}

    - name: 'Build Project 2'
      run: |
        func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME_2 }} --python
      working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_2 }}