name: Deploy to Azure Functions

on:
  push:
    branches:
      - main  # Replace with your deployment branch

env:
  AZURE_FUNCTIONAPP_NAME_1: multiple-functions-github-action-test-func1   # Replace with your first Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH_1: func1  # Replace with the path to your first project
  AZURE_FUNCTIONAPP_NAME_2: multiple-functions-github-action-test-func2   # Replace with your second Function App name
  AZURE_FUNCTIONAPP_PACKAGE_PATH_2: func2  # Replace with the path to your second project

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action Func1'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment Func1
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip Func1'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_1 }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action Func1'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_1 }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_1 }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_FUNC1 }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
    
    - name: 'Checkout GitHub Action Func2'
      uses: actions/checkout@v3

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment Func2
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip Func2'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_2 }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Run Azure Functions Action Func2'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME_2 }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH_2 }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_FUNC2 }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
